"""empty message

Revision ID: d9be846b44e4
Revises: 8206d7a098be
Create Date: 2021-01-04 17:08:38.105689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9be846b44e4'
down_revision = '8206d7a098be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_birthday', table_name='user')
    op.drop_index('ix_user_surname', table_name='user')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.VARCHAR(length=64), nullable=True))
    op.add_column('user', sa.Column('birthday', sa.DATE(), nullable=True))
    op.create_index('ix_user_surname', 'user', ['surname'], unique=False)
    op.create_index('ix_user_birthday', 'user', ['birthday'], unique=False)
    # ### end Alembic commands ###
